import "../global.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body className="flex flex-col h-screen">
        <header className="bg-slate-900 text-white w-full p-4">
          Users Root Layout Header
        </header>
        <div className="flex-1 p-4">{children}</div>
        <footer className="bg-blue-400 w-full p-4">
          Users Root Layout Footer
        </footer>
      </body>
    </html>
  );
}
