"use client";
import Link from "next/link";
import "../global.css";
import { usePathname } from "next/navigation";
// export const metadata = {
//   title: "users-Next.js",
//   description: "Generated by Next.js",
// };
const navLinks = [
  { id: 1, slug: "/", title: "Home" },
  { id: 1, slug: "/shop", title: "Shop" },
  { id: 1, slug: "/products", title: "Products" },
];
export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en" dir="ltr">
      <body className="flex flex-col h-screen">
        <header className="bg-slate-900 text-white w-full p-4">
          Users Root Layout Header
          <nav>
            <ul>
              {navLinks.map((item) => {
                const isActive = pathname == item.slug;
                return (
                  <li key={item.id}>
                    <Link
                      href={item.slug}
                      className={
                        isActive ? "font-bold text-violet-500" : "font-bold"
                      }
                    >
                      {item.title}
                    </Link>
                  </li>
                );
              })}
            </ul>
          </nav>
        </header>
        <div className="flex-1 p-4">{children}</div>
        <footer className="bg-blue-400 w-full p-4">
          Users Root Layout Footer
        </footer>
      </body>
    </html>
  );
}
